[package]
name = "merkle_sigs"
version = "1.0.0"
authors = ["Frederic Jacobs <github@fredericjacobs.com>"]

[dependencies]
ring = "^0.6.0"
lamport_sigs = "^0.1.2"

[dependencies.merkle]
version = "^1.1.0"
features = ["serialization-protobuf"]
