[package]
name = "merkle_sigs"
version = "1.2.0"
authors = ["Frederic Jacobs <github@fredericjacobs.com>"]

[dependencies]
ring = "^0.11.0"
lamport_sigs = "^0.3.0"

[dependencies.merkle]
version = "^1.3.0"
features = ["serialization-protobuf"]
