[package]
name = "merkle_sigs"
version = "0.1.0"
authors = ["Frederic Jacobs <github@fredericjacobs.com>"]

[dependencies]
rust-crypto = "^0.2.36"
lamport_sigs = "^0.1.1"

[dependencies.merkle]
git = "https://github.com/SpinResearch/merkle.rs"
features = ["serialization-protobuf"]
