[package]
name = "merkle_sigs"
version = "1.1.0"
authors = ["Frederic Jacobs <github@fredericjacobs.com>"]

[dependencies]
ring = "^0.9.7"
lamport_sigs = "^0.2.0"

[dependencies.merkle]
version = "^1.1.0"
features = ["serialization-protobuf"]
